# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "mobile"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: 
      "server/ToDo.Api"
      "server/ToDo.DbMigrator"
      "server/ToDo.Domain"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "webapp"
    schedule:
      interval: "daily"      
