services:
  todo.api:
    image: todo.api
    build:
      context: .
      dockerfile: ToDo.Api/Dockerfile
  
  todo.db-migrator:
    image: todo.db-migrator
    build:
      context: .
      dockerfile: ToDo.DbMigrator/Dockerfile
    depends_on:
      - todo.db