services:
  todo.api:
    image: todo.api
    build:
      context: .
      dockerfile: ToDo.Api/Dockerfile
    ports:
      - "5138:8080"
  
  todo.db-migrator:
    image: todo.db-migrator
    build:
      context: .
      dockerfile: ToDo.DbMigrator/Dockerfile