on:
  push: 
    branches: 
      - main
    paths: 
      - server/ToDo.DbMigrator/**
      - server/ToDo.Domain/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}-db-migrator

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.4.1
        with:
          context: server
          file: server/ToDo.DbMigrator/Dockerfile
          push: true
          tags: ${{steps.meta.outputs.tags}}