on:
  push: 
    branches: 
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}-api

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.4.1
        with:
          context: server
          file: server/ToDo.Api/Dockerfile
          push: true